# ----
# Site

title: VimeWorld.ru Public API
description: VimeWorld Public API documentation.
url: https://vimeworld.github.io
baseurl: /api-docs
google_analytics_key:
permalink: pretty

collections:
  common:
    title: Общее
    position: 1
  info:
    title: Данные
    position: 2
  api:
    title: Методы
    position: 3
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
